[workspace]
members = ["programs/solana-reputation-dao"]

[toolchain]
anchor_version = "0.29.0"

[programs.localnet]
solana_reputation_dao = "CiQgzVgLRjLC13vFjBnfsf6QGWnHgqGMZhrCnxZt95ha"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"